import type { Metadata } from "next";
import Image from "next/image";
import { ArrowDown, ArrowUpRight, Check, CheckCircle2, FileBadge2, FileCheck2, FileText, Fingerprint, Info, Landmark, LockKeyhole, PackageCheck, Ruler, ShieldCheck, Sparkles } from "lucide-react";
import TraceHeader from "../../components/TraceHeader";

export const metadata: Metadata = { title: "Dấu Ấn Thượng Triều Nguyễn · Hồ sơ truy xuất", description: "Hồ sơ truy xuất minh bạch của sản phẩm văn hóa Dấu Ấn Thượng Triều Nguyễn, mã STT-01." };
const BASE = "/traceability";
const product = { name: "Dấu Ấn Thượng Triều Nguyễn", code: "STT-01", version: "01-01", traceCode: "STT-01-HERITAGE", lot: "LOT-2026-08-001", serial: "00012345" };
const quickNav = [["02","Sản phẩm","product-info"],["03","Nguồn văn hóa","heritage"],["04","Chuyển hóa","design-development"],["05","Bảo chứng","attestation"],["06","Quyền tác giả","copyright"],["07","Hành trình","journey"],["08","Truy xuất","verification"],["09","Tài liệu","records"]] as const;
const journey = [
  ["01","Nguồn văn hóa","Mũ thượng triều triều Nguyễn","Tư liệu nguồn đã được lưu hồ sơ"],
  ["02","Phát triển thiết kế","Phương án STT-01","Có hồ sơ chuyển hóa thiết kế"],
  ["03","Bảo chứng văn hóa","Mã bảo chứng 01","Ghi nhận ngày 29/08/2026"],
  ["04","Sản xuất & kiểm tra","Lô LOT-2026-08-001","Dữ liệu minh họa — chờ đối soát"],
  ["05","Cấp mã & phát hành",product.traceCode,"Mã truy xuất hợp lệ trong hệ thống mẫu"],
] as const;
function Note({children,dark=false}:{children:React.ReactNode;dark?:boolean}){return <div className={`data-note ${dark?"dark":""}`}><Info size={14}/><span>{children}</span></div>}
function Heading({n,kicker,title,intro,light=false}:{n:string;kicker:string;title:string;intro:string;light?:boolean}){return <header className={`section-heading ${light?"light":""}`}><span className="section-number">{n}</span><div><p className="eyebrow">{kicker}</p><h2>{title}</h2><p>{intro}</p></div></header>}

export default function HeritageProductPage(){return <main className="trace-page">
  <TraceHeader/>
  <section id="overview" className="hero section-pad chapter-wine">
    <div className="hero-copy"><p className="eyebrow">01 — TỔNG QUAN</p><h1>Dấu Ấn<br/><em>Thượng Triều Nguyễn</em></h1><p className="hero-lead">Một lát cắt của mỹ thuật cung đình được chuyển hóa thành vật phẩm lưu niệm đương đại — với nguồn gốc, hồ sơ và hành trình có thể lần theo.</p><div className="hero-meta"><span><small>MÃ SẢN PHẨM</small><b>{product.code}</b></span><span><small>PHIÊN BẢN</small><b>{product.version}</b></span><span><small>MÃ TRUY XUẤT</small><b>{product.traceCode}</b></span></div><div className="hero-actions"><a href="#verification" className="primary-button">Truy xuất sản phẩm <ArrowDown size={15}/></a><a href="#heritage">Khám phá câu chuyện <ArrowUpRight size={14}/></a></div></div>
    <div className="hero-image"><span className="edition">STT<b>01</b></span><Image src={`${BASE}/heritage/product-studio.jpg`} alt="Sản phẩm Dấu Ấn Thượng Triều Nguyễn" width={1304} height={1206} priority/><div className="status-chip"><CheckCircle2/><span><small>TRẠNG THÁI HỒ SƠ</small><b>Mã truy xuất hợp lệ</b></span></div></div>
    <nav className="quick-nav" aria-label="Khám phá nhanh nội dung"><p><span>KHÁM PHÁ HỒ SƠ</span> Chọn một nội dung để đi nhanh</p><div>{quickNav.map(([n,t,id])=><a href={`#${id}`} key={id}><i>{n}</i><span>{t}</span><ArrowDown size={13}/></a>)}</div></nav>
  </section>

  <section id="product-info" className="content-section section-pad chapter-cream"><Heading n="02" kicker="THÔNG TIN SẢN PHẨM" title="Nhỏ trong kích thước, giàu trong lớp nghĩa." intro="Các thông tin định danh được dùng nhất quán trong toàn bộ hồ sơ, từ thiết kế, chứng nhận đến mã truy xuất."/><div className="details-grid"><div className="product-gallery"><Image src={`${BASE}/heritage/product-lifestyle.jpg`} alt="Dấu Ấn Thượng Triều Nguyễn trong bối cảnh sử dụng" width={1448} height={1086}/><Image src={`${BASE}/heritage/stt-01-product.png`} alt="Chi tiết sản phẩm STT-01" width={1304} height={1206}/></div><div className="specs"><article><PackageCheck/><small>LOẠI SẢN PHẨM</small><b>Vật phẩm nam châm trang trí</b></article><article><Ruler/><small>KÍCH THƯỚC</small><b>70 × 60 × 8 mm</b></article><article><Sparkles/><small>NGUỒN THIẾT KẾ</small><b>Mỹ thuật cung đình triều Nguyễn</b></article><article><Fingerprint/><small>MÃ / PHIÊN BẢN</small><b>{product.code} / {product.version}</b></article><div className="missing-data"><p className="eyebrow">MINH BẠCH DỮ LIỆU</p><p>Chất liệu và đơn vị sản xuất chưa có trong dữ liệu được xác minh. Hệ thống không tự suy đoán hoặc trình bày thông tin chưa được cung cấp.</p></div></div></div></section>

  <section id="heritage" className="content-section section-pad chapter-wine"><Heading light n="03" kicker="NGUỒN VĂN HÓA" title="Từ vật phẩm cung đình đến ký ức mang về." intro="Thiết kế khai thác ngôn ngữ tạo hình của mũ thượng triều triều Nguyễn — một dấu ấn của mỹ thuật cung đình Việt Nam."/><div className="heritage-grid"><figure><Image src={`${BASE}/heritage/heritage-hat-front.png`} alt="Mũ thượng triều nhìn từ phía trước" width={872} height={862}/><figcaption>TƯ LIỆU NGUỒN VĂN HÓA · MŨ THƯỢNG TRIỀU TRIỀU NGUYỄN</figcaption></figure><div className="heritage-story"><p className="eyebrow">DẤU VẾT THỊ GIÁC</p><blockquote>“Di sản không chỉ được lưu giữ; di sản còn được kể lại bằng ngôn ngữ của hôm nay.”</blockquote><p>Hình dáng hai cánh dựng cao, nhịp trang trí rồng – mây và bảng màu vàng, đỏ, lục trở thành những tín hiệu nhận diện quan trọng. Tư liệu nguồn được đặt cạnh sản phẩm để người xem có thể đối chiếu trực quan.</p><Note dark>Thông tin kiểm kê chỉ được hiển thị khi có tài liệu xác minh từ đơn vị lưu giữ.</Note></div></div></section>

  <section id="design-development" className="content-section section-pad chapter-cream"><Heading n="04" kicker="CHUYỂN HÓA THIẾT KẾ" title="Giữ tinh thần, thay đổi hình thức." intro="Quá trình thiết kế cô đọng đặc trưng thị giác của nguyên mẫu, đồng thời điều chỉnh tỉ lệ và cấu trúc để phù hợp với một vật phẩm đương đại."/><div className="design-grid"><div className="concept-board"><Image src={`${BASE}/heritage/stt-01-concept-board.png`} alt="Bảng phát triển ý tưởng của sản phẩm STT-01" width={1304} height={1206}/><span>HỒ SƠ PHÁT TRIỂN · PHƯƠNG ÁN STT-01</span></div><div className="design-notes"><p className="eyebrow">NGUYÊN TẮC CHUYỂN HÓA</p>{[["01","Dáng mũ tổng thể","Giữ trục đối xứng và hai cánh vươn cao làm nhận diện chính."],["02","Họa tiết rồng – mây","Cô đọng thành các lớp trang trí có thể đọc được ở kích thước nhỏ."],["03","Bảng màu cung đình","Vàng, đỏ và lục được cân bằng trên nền trung tính sang trọng."],["04","Tỉ lệ vật phẩm","Tinh chỉnh độ dày, bo cạnh và bề mặt cho trải nghiệm sử dụng hiện đại."]].map(([n,t,d])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>

  <section id="attestation" className="content-section section-pad chapter-wine"><Heading light n="05" kicker="BẢO CHỨNG VĂN HÓA" title="Một lớp hồ sơ cho giá trị văn hóa." intro="Bảo chứng ghi nhận mối liên hệ giữa sản phẩm và nguồn cảm hứng văn hóa; đây không phải chứng nhận chất lượng vật lý hay xuất xứ thương mại."/><article className="single-certificate"><div className="certificate-copy"><Landmark/><p className="eyebrow">ĐƠN VỊ BẢO CHỨNG</p><h3>Bảo tàng Lịch sử Quốc gia</h3><span className="seal-label">ĐÃ BẢO CHỨNG</span><dl><div><dt>Mã bảo chứng</dt><dd>01</dd></div><div><dt>Ngày ghi nhận</dt><dd>29/08/2026</dd></div><div><dt>Sản phẩm liên kết</dt><dd>{product.code} / {product.version}</dd></div></dl></div><div className="certificate-art"><Image src={`${BASE}/heritage/museum-logo.png`} alt="Biểu trưng Bảo tàng Lịch sử Quốc gia" width={338} height={338}/><p>CHỨNG THƯ BẢO CHỨNG<br/><b>GIÁ TRỊ VĂN HÓA</b><small>DẤU ẤN THƯỢNG TRIỀU NGUYỄN</small></p><Image src={`${BASE}/heritage/museum-red-seal.png`} alt="Dấu trên chứng thư bảo chứng" width={480} height={480}/></div></article></section>

  <section id="copyright" className="content-section section-pad chapter-cream"><Heading n="06" kicker="QUYỀN TÁC GIẢ" title="Ghi nhận quyền đối với tác phẩm thiết kế." intro="Giấy chứng nhận đăng ký quyền tác giả là tài liệu riêng, có phạm vi pháp lý khác với bảo chứng giá trị văn hóa."/><div className="copyright-grid"><div><FileBadge2/><p className="eyebrow">HỒ SƠ QUYỀN TÁC GIẢ</p><h3>Giấy chứng nhận đăng ký quyền tác giả</h3><span className="seal-label gold">ĐÃ ĐƯỢC CẤP CHỨNG NHẬN</span><dl><div><dt>Chủ sở hữu</dt><dd>DESIGNER</dd></div><div><dt>Số giấy chứng nhận</dt><dd>8854/2026/QTG</dd></div><div><dt>Ngày cấp</dt><dd>26/08/2026</dd></div></dl><Note>Thông tin hiển thị theo hồ sơ mẫu hiện có; cần đối chiếu bản gốc trước khi sử dụng cho mục đích pháp lý.</Note></div><Image src={`${BASE}/heritage/copyright-certificate.png`} alt="Giấy chứng nhận đăng ký quyền tác giả" width={768} height={1024}/></div></section>

  <section id="journey" className="content-section section-pad chapter-wine"><Heading light n="07" kicker="HÀNH TRÌNH SẢN PHẨM" title="Một chuỗi hình thành có thể lần theo." intro="Từng dấu mốc nối nguồn văn hóa, thiết kế, bảo chứng và phát hành. Nhãn trạng thái cho biết mức độ dữ liệu hiện có."/><div className="journey">{journey.map(([n,t,d,s],i)=><article key={n}><span className="step-number">{n}</span><div className="step-line"/><div>{i===0&&<Image src={`${BASE}/heritage/heritage-hat-rear.png`} alt="Chi tiết phía sau mũ thượng triều" width={878} height={890}/>}<FileCheck2/><small>{t}</small><h3>{d}</h3><p>{s}</p></div></article>)}</div></section>

  <section id="verification" className="content-section section-pad chapter-cream"><Heading n="08" kicker="TRUY XUẤT SẢN PHẨM" title="Một mã định danh, một hồ sơ minh bạch." intro="Kết quả cho biết mã đang tồn tại trong hệ thống mẫu và được liên kết với hồ sơ STT-01; không thay thế giám định vật lý sản phẩm."/><div className="verification-grid"><article className="code-card"><Fingerprint/><span className="valid"><Check/> MÃ TRUY XUẤT HỢP LỆ</span><h3>{product.traceCode}</h3><p>Liên kết với {product.name}, mã {product.code}, phiên bản {product.version}.</p><Note dark>Mã demo phục vụ trải nghiệm truy xuất và trình bày hồ sơ.</Note></article><article className="info-card"><p className="eyebrow">ĐỊNH DANH SẢN PHẨM</p><dl><div><dt>Tên sản phẩm</dt><dd>{product.name}</dd></div><div><dt>Mã / phiên bản</dt><dd>{product.code} / {product.version}</dd></div><div><dt>Lô sản xuất</dt><dd>{product.lot} <i>MINH HỌA</i></dd></div><div><dt>Serial</dt><dd>{product.serial} <i>MINH HỌA</i></dd></div></dl></article></div><div className="privacy-panel"><LockKeyhole/><div><b>Lịch sử truy xuất tôn trọng quyền riêng tư</b><p>Hệ thống chỉ hiển thị thời điểm và trạng thái xác thực tổng quát. Địa chỉ IP, tên thiết bị và định danh cá nhân không được công khai.</p></div></div></section>

  <section id="records" className="records section-pad chapter-wine"><div><span className="section-number">09</span><p className="eyebrow">TÀI LIỆU XÁC THỰC</p><h2>Tài liệu được tổ chức tại một nơi.</h2><p>Chứng thư bảo chứng, giấy chứng nhận quyền tác giả và tư liệu nguồn được liên kết cùng một hồ sơ sản phẩm.</p></div><div>{[["Chứng thư bảo chứng","Bảo tàng Lịch sử Quốc gia"],["Giấy chứng nhận quyền tác giả","Số 8854/2026/QTG"],["Hồ sơ ảnh nguồn văn hóa","Mũ thượng triều triều Nguyễn"],["Hồ sơ thiết kế sản phẩm","Phương án STT-01"]].map(([t,s])=><div className="record-row" key={t}><FileText/><span><b>{t}</b><small>{s}</small></span><ShieldCheck/></div>)}</div></section>

  <footer className="site-footer"><div className="footer-brand"><span className="brand-seal">ẤN</span><span><b>DẤU ẤN DI SẢN VIỆT</b><small>NỀN TẢNG TRUY XUẤT SẢN PHẨM VĂN HÓA</small></span></div><div className="footer-info"><p><b>Thông tin nền tảng</b></p><a href="#overview">Giới thiệu</a><a href="#verification">Truy xuất sản phẩm</a><a href="#records">Hồ sơ xác thực</a></div><div className="footer-operator"><Image src={`${BASE}/heritage/vtc-logo.png`} alt="VTC" width={4000} height={2160}/><span><small>NỀN TẢNG ĐƯỢC VẬN HÀNH BỞI</small><b>VTC</b><em>Đơn vị công nghệ và truyền thông số</em></span></div><a className="back-top" href="#overview">Về đầu trang <ArrowUpRight size={14}/></a><p className="footer-bottom">© 2026 VTC · Thông tin trên trang thuộc hồ sơ trình diễn của sản phẩm STT-01.</p></footer>
</main>}
